name: 'Check commit message'
description: 'check the commit message`s format every time pull_request happend'
author: 'HikawaRin'
inputs:
  use_strict:
    description: 'If set this property true the pull_request will be cancled automatic'
    default: false
  token:
    description: "Used to cancel pull_request which not match format. Since there's a default, this is typically not supplied by the user."
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'index.js'