name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
        check-latest: true
    - run: npm install
    - run: npm test
    - run: chmod -R +x ./
    - run: ls /home/runner/work/check-commit-action/check-commit-action
    - uses: HikawaRin/check-commit-action@master
      id: 'lint'
